### ISSUE TITLE
Module missing from CPAN index

### ISSUE THREAD

**Issue by jplindstrom** [skx/CGI--Session--Driver--redis#1]
Hi,

It looks like CGI::Session::Driver::redis isn't properly indexed, so it's not available to install from CPAN.

It's visible here for some reason:
http://search.cpan.org/~skx/CGI-Session-Driver-redis-0.5.1/

but not here:
https://metacpan.org/search?q=CGI%3A%3ASession%3A%3ADriver%3A%3Aredis&size=20

and it's not actually available to install using e.g. cpanm.

**Comment by skx** [comment]
Thanks for the report.  I think I've tracked down the problem:

```
 module : CGI::Session::Driver::redis
 version: 0.005001 in file: CGI-Session-Driver-redis-0.5.1/lib/CGI/Session/Driver/redis.pm

 status : Not indexed because CGI-Session-Driver-redis-0.5/lib/CGI/Session/Driver/redis.pm
 in S/SK/SKX/CGI-Session-Driver-redis-0.5.tar.gz has a higher version number (0.5)
```

In short version 0.5.1 is _lower_ than 0.5, for some reason.

I'll get this fixed by releasing 0.6 tonight, or over the weekend.  Then I'll go check my other modules for more silent failures.

Thanks again!
