### ISSUE TITLE
Missing File::ShareDir::Install in dependencies ?

### ISSUE THREAD

**Issue by Difegue** [skx/CGI--Session--Driver--redis#2]
Trying to install this with cpanm fails.  
Looking at the log shows it looks for File::ShareDir::Install but can't find it.  
Installing File::ShareDir::Install before trying to install CGI::Session::Driver::redis fixes the issue.

**Comment by skx** [comment]
The fix is landed here now and on [my mirror](https://git.steve.org.uk/cpan/CGI--Session--Driver--redis) and I've pushed a new release to CPAN.

Thanks for the report!
